### ISSUE TITLE
dot -Tpng -o test.png test.dot - command not found

### ISSUE THREAD

**Issue by sbonaretti** [usc-isi-i2/ontology-visualization#6]
Hi, 

When I copy/paste `./ontology_viz.py -o test.dot test.ttl -O ontology.ttl` in my terminal, I get:   
```
[WARNING] Class http://dig.isi.edu/Time_Span doesn't exist in the ontology!
[WARNING] Property http://dig.isi.edu/at_some_time_within_date doesn't exist in the ontology!
```

When I copy/paste `dot -Tpng -o test.png test.dot`, I get:    
```dot: command not found``` 

Any suggestions?
Thanks!

**Comment by GreenRobot777** [comment]
install `graphviz`
